Updated package.json with TypeScript 4.2.4; Implement song details parsing
kobayashley/blues pull request #23
Opened 2021-04-30 01:49 UTC by kobayashley

Resolves #2

2021-04-30 04:16 UTC, braxtonhall requested changes
Overall looking great! Just a few minor nitpicks that should be really easy to fix in a single commit.

2021-04-30 04:16 UTC, braxtonhall commented on src/controllers/RythmController.ts
> +    } else if (now > start + (length/2)) {
I really should add this to the linter, but could we have proper spacing between language terms?

This would look like `length / 2` here!

2021-04-30 04:16 UTC, braxtonhall commented on src/controllers/RythmController.ts
> +    Log.debug(`hours: "${hours}", minutes: "${minutes}", seconds: "${seconds}"`);
Nitpick, but might be nice to consistently have capitalization in log messages

2021-04-30 04:16 UTC, braxtonhall commented on src/controllers/RythmController.ts
> +// "`Requested by:` user#1234" | "`Requested by:` nickname (us (er#1234)"
oops! can we revert this change?

2021-04-30 04:16 UTC, braxtonhall commented on src/controllers/RythmController.ts
> +        name = inputName.slice(parenIndex+1, -1);
Same here with the spacing in the math

2021-04-30 04:16 UTC, braxtonhall commented on src/controllers/RythmController.ts
> +    Log.debug(`pareRequester name: ${name}`);
Spelling 👀

2021-04-30 04:16 UTC, braxtonhall commented on src/controllers/RythmController.ts
> +    const secondsMS = seconds*1000;
Spacing!

2021-04-30 21:08 UTC, braxtonhall commented
I resolved a conflict for you on this branch, so don't forget to pull before making changes.
I really shouldn't have done that, but I felt bad for merging the other branch before this one

2021-05-02 03:44 UTC, kobayashley commented on src/controllers/RythmController.ts
> +    Log.debug(`pareRequester name: ${name}`);
also spacing !

2021-05-02 03:57 UTC, braxtonhall approved these changes
Looking great! You're good to merge
Don't forget to link your commit messages to something with more context (like #23) when available though :)

2021-05-03 05:43 UTC, merged